version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-app
    file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 20
  AfterInstall:
    - location: scripts/install_dependencies.sh
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 20
